repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.88.4 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
    hooks:
      - id: terraform_fmt
      - id: terraform_tflint
        args:
          - --args=--module
          - --args=--enable-rule=terraform_documented_variables
          - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
      - id: terraform_validate
        args:
          - --args=-json
          - --args=-no-color
