name: App Service Deployment
on:
  workflow_dispatch
env:
  WEBAPP_NAME: "appavddevuan1"
  RESOURCE_GROUP: "app-svc-test-plan"
  SLOT_NAME: staging  # Create a slot on your web app called "staging"
permissions:
  id-token: write
  contents: read
#    inputs:
#      subscription_name:
#        description: Subscription Name to be created
#        type: string
#        required: true
#      team_name:
#        description: The name of the team used to name other resources
#        type: string
#        required: true
#      management_group_name:
#        description: The name of the existing management group associated with the new subscription
#        type: string
#        required: true



jobs:
  Build-Package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: workdir
        run: pwd
      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: microsoft
      - name: Build app
        run: mvn clean package
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.war'

  Deploy-Staging:
    runs-on: ubuntu-latest
    needs:
      - Build-Package
    continue-on-error: false
    steps:
      - name: login
        uses: Azure/login@v2.1.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: java-app

      - name: Deploy to stage env
        uses: azure/webapps-deploy@v1
        id: deploy-to-stage
        with:
          app-name: ${{ env.WEBAPP_NAME }}
          package: '*.war'
